version: '3.8'

services:
  # Servicio MLflow Server
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow-db-data:/mlflow/mlruns
      - mlflow-artifacts-data:/mlflow/mlartifacts
    networks:
      - traductor-net
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:///mlflow/mlruns
      --default-artifact-root file:///mlflow/mlartifacts
    

  # Servicio App de Traducción
  app-traductor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traductor-app
    ports:
      - "7860:7860"
    volumes:
      - mlflow-db-data:/app/mlruns
      - mlflow-artifacts-data:/app/mlartifacts
    environment:
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    networks:
      - traductor-net
    depends_on:
      - mlflow-server 
    restart: unless-stopped

# Definición de red
networks:
  traductor-net:
    driver: bridge

# Definición de volúmenes
volumes:
  mlflow-db-data:
    driver: local
  mlflow-artifacts-data:
    driver: local